### ISSUE TITLE
Include 'jing' in docker image

### ISSUE THREAD

**Issue by abalage** [SUSE/dice#10]
Please bare with me I am just started to work with dice and kiwi. :)
I got this build.log because I made a mistake in config.xml

```
[ DEBUG   ]: 12:09:01 | EXEC: [mkdir -p /tmp/kiwi_build_20161201-6748-1uyl4gx.dice/build/image-root]
[ INFO    ]: 12:09:01 | Loading XML description
[ DEBUG   ]: 12:09:01 | EXEC: [jing /usr/lib/python3.5/site-packages/kiwi/schema/kiwi.rng /tmp/tmp_u6ir_nr]
[ DEBUG   ]: 12:09:01 | "jing": in paths "/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin" exists: "False" mode match: not checked
[ DEBUG   ]: 12:09:01 | EXEC: Command "jing" not found in the environment
[ INFO    ]: 12:09:01 | Schema validation failed. See jing report:
[ ERROR   ]: 12:09:01 | Unexpected error:
Traceback (most recent call last):
  File "/usr/bin/kiwi", line 11, in <module>
    load_entry_point('kiwi==8.24.4', 'console_scripts', 'kiwi-ng')()
  File "/usr/lib/python3.5/site-packages/kiwi/kiwi.py", line 54, in main
    App()
  File "/usr/lib/python3.5/site-packages/kiwi/app.py", line 35, in __init__
    task_class().process()                                                                                                                                                   
  File "/usr/lib/python3.5/site-packages/kiwi/tasks/system_build.py", line 102, in process
    self.command_args['--description']
  File "/usr/lib/python3.5/site-packages/kiwi/tasks/base.py", line 128, in load_xml_description
    self.xml_data = description.load()
  File "/usr/lib/python3.5/site-packages/kiwi/xml_description.py", line 105, in load
    self._get_validation_details()
  File "/usr/lib/python3.5/site-packages/kiwi/xml_description.py", line 134, in _get_validation_details
    log.info('--> ' + cmd.output)
TypeError: Can't convert 'NoneType' object to str implicitly
```

Once I manually installed jing and get a copy of kiwi.rng on my local system I realized what the problem was, anyway it would be nice to include jing in the docker image too.

```
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
opensuse/dice       latest              abe115e11a07        5 weeks ago         577.8 MB
```

**Comment by schaefi** [comment]
yeah the jing thing however pulls in the java stack and I thought it would be nice to keep the docker container as small as possible.

I'll give it a try and see how big it will grow

**Comment by schaefi** [comment]
I have added jing to the container and will upload the result to dockerhub today. I'll let you know when I'm finished

**Comment by schaefi** [comment]
docker push is running

docker push opensuse/dice:latest
The push refers to a repository [docker.io/opensuse/dice]
2758074f5a2c: Pushing 20.91 MB/731.7 MB

adding jing significantly changes the size, however I'll give it a try
